### ISSUE TITLE
イベントページ作成

### ISSUE THREAD

**Issue by emorima** [railsgirls-jp/events#1]
- [x] 日時・場所決める
- [x] 世界に向けて開催を宣言する http://railsgirls.com/inyourcity
- [x] railsgirls/railsgirls のリポジトリの権限を hsbtさんにもらう
- [x] イベントページを作成して公開する 
  (独自ロゴは必須ではありません。最初はデフォルトのロゴで公開して、ロゴを作れたら更新しましょう!)

**Comment by emorima** [comment]
@hsbt 
@zanaka に本家リポジトリの権限の追加をお願いしたいです！

**Comment by hsbt** [comment]
追加しておきました! ついでに @emorima を owner にもしておきました。

**Comment by zanaka** [comment]
@hsbt 初めまして！ありがとうございます！！
