### ISSUE TITLE
ロゴ作成

### ISSUE THREAD

**Issue by emorima** [railsgirls-jp/events#11]
個別にロゴを作るようでしたら、イベントサイトに載せて、ステッカーやTシャツに使いましょう～

**Comment by zanaka** [comment]
現在，Okinawaのロゴを提案・作成してもらっていますー🙌

**Comment by emorima** [comment]
@torobi @MiwakoEmoto @shokola 

沖縄でステッカー作成するのにご相談したいです！
カスタムサイズのステッカーを作成したいのですが、イベント開催の 11/9 に間に合わせるとしたら、どこで作るとお勧めとかいう情報お持ちでしょうか～？

**Comment by emorima** [comment]
教えてもらったり、過去に使った場所

https://www.digitaprint.jp/label_price02.php
https://www.graphic.jp/lineup/ondemand/sticker.php

**Comment by neko314** [comment]
グラフィックはデータ入稿前に納期と値段が出るのですが、10thと同じサイズで50枚で計算すると2700円くらいで、納期が5日と出ました。

沖縄までの配送日数がおそらく+数日かかるのを踏まえても、間に合わせることはできるかもしれません。

今回、確認したいことがあったので電話で問い合わせしたんですけど、なにかあれば電話でも要望を受けると言われたので、"こういうステッカーを作って沖縄での納期に間に合わせたい"と電話するという手もありそうです〜
（オンラインで注文するときにもコメント入れる欄があるのでそれに要望を記載することはできます）

**Comment by MiwakoEmoto** [comment]
日曜出荷のところ見つけました。
お願いしたことがないので、なんとも言えませんがご参考まで。
https://www.wave-inc.co.jp/order/index.php?main_page=page_404402

**Comment by zanaka** [comment]
みなさま情報ありがとうございます🙇‍♀️

**Comment by emorima** [comment]
digita で作成して、かわいいのできました！
