### ISSUE TITLE
スポンサー募集

### ISSUE THREAD

**Issue by emorima** [railsgirls-jp/events#13]
Google Form共有して公開済み

8/14時点、3社のお申込みあり

**Comment by zanaka** [comment]
パートナーを追加しました！
railsgirls/railsgirls#1569

**Comment by emorima** [comment]
マージしました！

**Comment by zanaka** [comment]
パートナーの追加と募集フォームを掲載しました！
railsgirls/railsgirls#1576

**Comment by zanaka** [comment]
9/27時点で，5社のお申込み有
連絡して行きます！

**Comment by zanaka** [comment]
10/15時点で，7社のお申込み有です🙇‍♀️🙌✨

**Comment by emorima** [comment]
フォームcloseしました！
