### ISSUE TITLE
イベント宣伝

### ISSUE THREAD

**Issue by thatblue** [railsgirls-jp/events#15]
- [x] チラシ、ポスターを作成する
- [x] チラシ、ポスターの配布を依頼しに行く

**Comment by thatblue** [comment]
@emorima @mikicosmos @m-kaiya
仙台のIT系Webメディアさまから取材依頼をいただきました。
Rails Girls Sendaiの運営チームが仙台のカフェで実際に集まっての座談会を記事にする、ということでしたがみなさま参加可能そうでしょうか？
リモートでの参加が可能か聞いてみたのですが、「実際に現地に集まって欲しい」と言うことでしたので、@emorima さんには移動のご負担をかけてしまう形になりそうですが…
ちょっと取材を受けるのが初めてでどういうものなのかが分かってないのですが、交通費等出るのかは確認してみます。

過去の掲載例としてはこのような感じだそうです。
https://sendai-inc.com/people/sendai-coffee-talk-vol-1/

**Comment by emorima** [comment]
@thatblue おぉぉ～すばらしい!!

日程合うようでしたら、是非行きたいです!
9/15(土)、9/22(土) は、予定があるので難しいですが、その他でしたら日帰りもできます!
(仙台、案外近いことは、RubyKaigi で学習済み!)

**Comment by mikicosmos** [comment]
@thatblue 知ってるメディアです！日程が合えば参加できますよ～

**Comment by kaiyar** [comment]
@thatblue わたしも日程が合えば参加できますー！

**Comment by thatblue** [comment]
@emorima @mikicosmos @kaiyar 
みなさまありがとうございますー！では全員参加の方向でスケジュール調整してみます。

**Comment by thatblue** [comment]
当日のスケジュール次第とは思いますが、せっかくなので時間が取れたらご飯など食べに行きたいですね:laughing:

**Comment by thatblue** [comment]
@emorima @mikicosmos @kaiyar
日程なのですが、どうやら10月になりそうとのことでした、思ったより先だった…
1stの直接的な宣伝と言うよりは、今後に向けての種まきという位置付けになりそうですね。

**Comment by mikicosmos** [comment]
@thatblue 10月前半であれば、まだ満席になっていなければ、集客にも使えそうですね！
せっかくなのでご飯も食べましょ〜

**Comment by emorima** [comment]
@thatblue 10月了解です!

10/12-13 でTokyo開催があるのですが、それ以外であれば今のところ調整可能です!

種まき！いいですね！

Rails Girls のイベントだけですと、1回だけになってしまって、
その後どうやって学習の継続をサポートするかも課題になるので、
そこらへんのお話も、🍚食べながらできたらいいなって思っています！

**Comment by thatblue** [comment]
@mikicosmos @emorima 
ありがとうございます、よろしくお願いいたします！
詳しい日程調整の連絡が来ましたら、改めてご連絡いたします。

> Rails Girls のイベントだけですと、1回だけになってしまって、
> その後どうやって学習の継続をサポートするかも課題になるので、
> そこらへんのお話も、rice食べながらできたらいいなって思っています！

ありがとうございます、考えなきゃと思いつつ、現状まだまだイベント開催に関することしか考えられてないので、とても助かります！

**Comment by thatblue** [comment]
https://lets-go-study-meeting.connpass.com/event/99050/
宣伝かねて、でこちらのイベントにてLT枠もらったので、ちょっと喋ってきます！

**Comment by thatblue** [comment]
@emorima @mikicosmos @kaiyar 
ロゴを置いた共有フォルダと同じところにチラシ(兼ポスター)のPDFファイルを置いておきましたー
自宅でいくらか印刷して、仙台のコワーキングスペース様などに置かせていただこうと思っていますが、
よろしければ使ってください！そのまま印刷するとA4サイズになります。
自宅でためしにプリントした感じでは、QRコードを読ませるならA5サイズがギリギリかなぁという感じでした。

**Comment by mikicosmos** [comment]
@thatblue LT枠で宣伝って手があったんですねー。お手数ですがよろしくお願いします！
そしてポスターありがとうございます！！素敵です！！

**Comment by thatblue** [comment]
今回スポンサーもしていただいている、コワーキングスペースのノラヤさまからチラシ置くよっていうご連絡をいただいたので、今日お店に伺うついでに渡しに行ってきます！

**Comment by mikicosmos** [comment]
@thatblue ありがとうございますー！よろしくお願いしますー！

**Comment by thatblue** [comment]
参加者・コーチ周りの各種募集期間が終了したので、こちらのissueをクローズします。
