### ISSUE TITLE
Doorkeeper準備

### ISSUE THREAD

**Issue by emorima** [railsgirls-jp/events#2]
- [x] Doorkeeper で、 Rails Girls Okinawaアカウント取得
- [x] RailsGirls Japan をコミュニティオーナーに設定する
- [x] コーチ募集イベントを作成する
- [x] 参加者募集イベントを作成する

**Comment by emorima** [comment]
https://railsgirls-okinawa.doorkeeper.jp/

@springaki さんが作ってくれました。
@zanaka 確認お願いします。

**Comment by springaki** [comment]
@zanaka Doorkeeperの管理者にするのでメールアドレス教えてください ! シャウト時のヤツでよければそれで設定します (大学のメールアドレスになってたみたいなのでいいのかな？という念のための確認)

**Comment by zanaka** [comment]
@emorima さん，@springaki さん，ありがとうございます！
シャウト時のメールアドレスで大丈夫です。よろしくお願いします！

**Comment by springaki** [comment]
@zanaka 了解です。招待しましたので確認おねがいします 😸

**Comment by zanaka** [comment]
@springaki 確認しました！コーチ，参加者の募集イベント作成していきます😆

**Comment by springaki** [comment]
@zanaka 参加人数に上限など特にありませんが、最初はコーチとマンツーマンくらいの人数にしておいた方が良いのではと思います。特にイベント開催慣れしているわけでなければ、最初は全体で20-30くらいの人数がちょうどいいんじゃないかなーという感覚です。

@zanaka さんやバックアップしてくれる沖縄のコミュニティがどんな感じかにも依存するので、ご参考まで。

https://github.com/railsgirls-jp/events/issues/4#issuecomment-411574868 あたりも参考にしてみてください。

**Comment by zanaka** [comment]
@springaki 承知しました！イベント開催が今回初めてなので，色々と参考になります！ありがとうございます。

**Comment by zanaka** [comment]
参加者募集イベントを作成しました！
https://railsgirls-okinawa.doorkeeper.jp/events/78851

コーチ募集イベントも作成しました！
https://railsgirls-okinawa.doorkeeper.jp/events/78854

@emorima さんを railsgirls-okinawa に招待しました！
@springaki ご確認お願いします！

**Comment by springaki** [comment]
よいのでは〜。特に意見ありませんでした 😊

**Comment by zanaka** [comment]
ありがとうございます！
それでは公開して宣伝していきます！💪
