### ISSUE TITLE
GitHubノベルティ

### ISSUE THREAD

**Issue by emorima** [railsgirls-jp/events#20]
GitHub 年間スポンサーのノベルティ (以下) があるので、
当日までに何らかの方法でお渡しします。

* ステッカー
* gitコマンドのチートシート(あれば)
* GITHUB FLAVORED MARKDOWN , THE GITHUB FLOW のカード

**Comment by thatblue** [comment]
ありがとうございます！
イベント開催側なのに普通に欲しいノベルティで、ちょっとワクワクします:eyes:
別件で会場のメンバーズエッジさまに必要物品の送付OKの確認をしてしていたので、郵送/宅急便が必要な場合は別途送付先をご連絡しますー
