### ISSUE TITLE
コーチ打ち合わせ

### ISSUE THREAD

**Issue by thatblue** [railsgirls-jp/events#21]
- [x] 日程を決める(コーチ申し込み締め切りが10/12なので、それ以降)
- [x] みんなのウェディングさまのリモートLT接続テスト→インストール・デイに延期
    - [x] 日程調整のご案内をする 
- [x] 打ち合わせの内容をまとめる

**Comment by thatblue** [comment]
@emorima @mikicosmos @kaiyar
コーチ打ち合わせの日程をそろそろ決めたいなーと思っておりました。
平日夜の方が時間を取りやすいのかなーと思っておりましたが、みなさまご都合はいかがでしょうかー

あと、イベント開催時に参加者の方にも入っていただくのを見越して、コーチの方を入れてSlackグループとか作った方がいいかなぁとか思っておりました。

**Comment by mksmz** [comment]
@thatblue 平日夜でしたら、10月後半は今のところほぼ大丈夫なので、候補日決まったら調整できると思います！slackもあってもいいですねー。

**Comment by kaiyar** [comment]
@thatblue @mksmz 
私は今のところ、平日夜でしたら10/22,23しか参加できずです。もし都合合わない場合は、私を無視して調整してもらって大丈夫です。（内容はコーチの芦名さんから共有してもらうこともできますので）

slackいいですね 👍

**Comment by thatblue** [comment]
@mksmz @kaiyar @emorima 
ありがとうございます！では、10/23を第一候補として調整したいと思いますー。
メンバーズエッジさまにご挨拶に行った際、コーチ打ち合わせで会場をお借りしたいという旨は大雑把にお伝えしていたので、改めて相談してみます。

**Comment by thatblue** [comment]
@emorima 現状まだ募集中で未確定という感じでしたが、現時点でコーチに立候補いただいている方もSlackに招待してしまって大丈夫ですかね、以降新しくお申し込みいただいたら順次招待する感じで。

**Comment by thatblue** [comment]
@mksmz @kaiyar @emorima
10/23の夜でメンバーズエッジさまの会場お借りできました！

**Comment by thatblue** [comment]
@mksmz @kaiyar @emorima
Slackのワークスペースを作ったので、Doorkeeperに登録したメールアドレスに招待お送りしました！

**Comment by thatblue** [comment]
無事にMTG終了しましたので、issueクローズします。
ありがとうございましたー！:bow:
