### ISSUE TITLE
イベントページ作成

### ISSUE THREAD

**Issue by emorima** [railsgirls-jp/events#3]
- railsgirls/railsgirls.git のリポジトリ権限を追加する
- イベントページを作成して公開する
(独自ロゴは必須ではありません。最初はデフォルトのロゴで公開して、ロゴを作れたら更新しましょう!)

**Comment by thatblue** [comment]
ありがとうございます、こちらでもよろしくお願いしますー

**Comment by emorima** [comment]
@thatblue railsgirls/railsgirls のアクセス件追加しました！

**Comment by thatblue** [comment]
ありがとうございます、確認しました！
日程は11/2(金)-11/3(土)でメンバーズエッジさまと調整しました！

**Comment by thatblue** [comment]
@emorima 
railsgirls/railsgirlsのリポジトリへPR作成しました。
現状アサインを設定していなかったのですが、emorimaさんに設定しても大丈夫でしょうか？
https://github.com/railsgirls/railsgirls/pull/1564

**Comment by emorima** [comment]
@thatblue 

確認して、OKそうなのでマージしました！ 
実は、events.html , index.html にもUpcoming Events でイベント情報掲載しているので、
後で、シュッとデフォルトロゴで対応しちゃいますね。

**Comment by thatblue** [comment]
@emorima 
了解です、ありがとうございます！
本体ページの方見落としてましたすみません、ありがとうございます。
会場のメンバーズエッジさまにも掲載内容問題ないかご確認依頼の連絡します！

**Comment by thatblue** [comment]
メンバーズエッジさまに掲載内容OKいただきました！

**Comment by thatblue** [comment]
@emorima 
すみません、issueをクローズしたり、新しいissueを作ってSendaiラベルをつけたりする権限が私にないみたいでした。
お手数をおかけして申し訳ありませんが、可能であればそのあたりの権限をいただけると嬉しいです。
(そしてもし私の操作だけで作業できるようになるのであれば申し訳ないです…)

**Comment by springaki** [comment]
@thatblue 付けてみましたが、どうでしょう？

**Comment by thatblue** [comment]
@springaki ありがとうございます、closeボタンなど表示されたのを確認しました！

**Comment by thatblue** [comment]
イベントページ作成の作業がひと段落しましたので、こちらのissueはクローズします。
修正対応は各タスクのissueで管理します。
