### ISSUE TITLE
 Doorkeeper準備

### ISSUE THREAD

**Issue by springaki** [railsgirls-jp/events#4]
- [x] Doorkeeper で、 Rails Girls Sendaiアカウント取得
- [x] RailsGirls Japan をコミュニティオーナーに設定する
- [x] コーチ募集イベントを作成する
- [x] 参加者募集イベントを作成する

**Comment by springaki** [comment]
@thatblue Doorkeeper 作って管理者招待しておきました !

**Comment by thatblue** [comment]
@springaki ありがとうございます、招待確認しました！

**Comment by emorima** [comment]
Doorkeeperの募集ページを作るときに、予定人数が多い場合は抽選となることの記載をお願いします。

(抽選漏れた方が、「なんだ抽選だったのか」と後でガックリするのは切ないので。)

**Comment by thatblue** [comment]
承知しました、ありがとうございます。

**Comment by thatblue** [comment]
他地域のイベントページを参考にして、参加者募集イベントを作成しました！
https://railsgirls-sendai.doorkeeper.jp/events/78698

**Comment by thatblue** [comment]
コーチ募集イベントも作成しました！
https://railsgirls-sendai.doorkeeper.jp/events/78699

**Comment by emorima** [comment]
未公開は管理者じゃないのと見えないので、見れなかったw
OKそうなら公開して、イベントページもUPしてくださ～い

**Comment by thatblue** [comment]
あっ、しまったすみません、そう言えばそうでした…
取り急ぎ公開状態にします！
イベントページは手元のリポジトリで修正していたので、夜にでもPR出しますー

**Comment by thatblue** [comment]
@emorima というかDoorkeeperの管理者招待します、GitHubのプロフィールに書いてあるメールアドレスに招待送る形で大丈夫でしょうか？
(RailsGirls Japanのアカウントがオーナーになっていたので、あまり深く考えずに見られるものと思ってました、すみません…)

**Comment by thatblue** [comment]
仙台スタッフの@mikicosmos さんと@m-kaiya さんも招待しておきますー(いまメールアドレス確認中でした)

**Comment by emorima** [comment]
@thatblue GitHubに記載してあるメールアドレスに送ってくださいー。 🙇‍♀️

**Comment by thatblue** [comment]
@emorima  招待メール送りました！

**Comment by emorima** [comment]
@thatblue ありがとうございます！

Doorkepper確認しました！よさそうです～！ (20名すごい!!!)

**Comment by thatblue** [comment]
@emorima ありがとうございますー、一応最大20名とはしているのですが、実際定員まで申し込みがあるかどうかはちょっと未知数なところがあります:confounded:
会場のキャパシティとしては大丈夫というお話は頂いているので、もしかしたらはじめは10人くらいで募集して、たくさん応募頂いたらコーチの集まり具合など見て増席した方がいいのかもしれないなーと思い始めました。

**Comment by thatblue** [comment]
ということで、募集定員を10名にしました！
参加者・コーチの申込状況に応じて増席可能そうなら対応する方針にしたいと思います。

**Comment by thatblue** [comment]
Doorkeeperのイベント公開しました！

**Comment by emorima** [comment]
マージしました！

**Comment by thatblue** [comment]
ありがとうございます、まずは宣伝頑張りますー！

**Comment by thatblue** [comment]
コーチ募集・参加者募集のイベント作成がひと段落しましたので、こちらのissueはクローズします！
