### ISSUE TITLE
ロゴ作成

### ISSUE THREAD

**Issue by emorima** [railsgirls-jp/events#6]
Rails Girls デフォルトのロゴでもかわいいので、それを使ってもよいのですが、
初めての東北！初めての仙台！ 開催 なので、個別に仙台用ロゴを作るようでしたら、
イベントサイトに載せて、ステッカーやTシャツに使いましょう～

**Comment by thatblue** [comment]
@emorima @mikicosmos @m-kaiya
![logo_example](https://user-images.githubusercontent.com/1575990/44310746-6aa16d00-a416-11e8-913a-ef0e47281f26.png)
Ruby x 仙台 x 女性、でとても安直なのですが、ちょっと描いてみました！

**Comment by mikicosmos** [comment]
わー！絵書けるんですね！
仙台ってわかりやすいしかわいいです！！

**Comment by emorima** [comment]
すっごくかわいい!!! 😍

**Comment by m-kaiya** [comment]
可愛い！いいですね❤️

**Comment by thatblue** [comment]
ありがとうございますー！
少し余裕ができたので、隙をみてもうちょっとだけ調整します！

**Comment by thatblue** [comment]
![default](https://user-images.githubusercontent.com/1575990/44358803-ff789900-a4f0-11e8-986d-c421b7ad07a2.png)
調整してこんな感じになりました！

**Comment by thatblue** [comment]
問題なさそうであれば、こちらでイベントページ等に反映したいと思います！

**Comment by thatblue** [comment]
イベントページに反映してPull Request出しましたー
https://github.com/railsgirls/railsgirls/pull/1572

**Comment by thatblue** [comment]
スポンサー申込フォームなどを置いてある共有フォルダに作った画像を一通りアップロードしておきました。
もし必要であればぜひ使ってください！

**Comment by emorima** [comment]
マージしました！反映もされていますー。

**Comment by thatblue** [comment]
@emorima @mikicosmos @m-kaiya 
ありがたいことに現時点でスポンサーさまの申込を2件いただいているので、ステッカーくらいなら作れるかな？と思っていました。

個人的によくステッカー印刷をお願いしているデジタだと、大体100枚発注して4000円くらいになります。
https://www.digitaprint.jp/seal_top.php
